spring.application.name=result-service
server.port=8084

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/result_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=MyVerySecretKeyMyVerySecretKeyMyVerySecretKeyMyVerySecretKey

logging.level.com.example.result_service=DEBUG